# LightChatBubbles plugin configuration file
# Read project page for aditional info = https://dev.bukkit.org/projects/light-chat-bubbles

# since name tags are visible to everyone in world, only server wide configurations are possible
# read speed analysis taken from: http://iovs.arvojournals.org/article.aspx?articleid=2166061

# floating text lines in chat bubble above player's head
maxBubbleHeight: 3

# max chat bubbles width, longer words won't be truncated and will still appear whole in a single line
maxBubbleWidth: 15

# ticks to wait between bubble chats, about a blink, default 5 ticks (250 msec)
bubblesInterval: 5

# characters per minute, considering an average of 5 chars per word (4 letters + 1 space)
readSpeed: 800

# i had noted there is an additional previous time of about 2 word (10 chars) to notice message and position eyes
handicapChars: 10

# will chat messages only appear in chat bubbles and won't echo on chat window?
disableChatWindow: false

# chat formatting codes for messages, without &. Examples: "EL", "C", "L"
# consider using "&e&l{message}" in chatFormat. This is here only for backwards compatibility purposes
chatFormat: ""

# chat message format. Applied for each message. Set to "SERVER" to make it the same as in chat.
# examples: "&e{player} said: &f{message}", "{player}: {message}", "&l{message}", "SERVER"
messageFormat: "{message}"

# bubble format. Applied to every bubble.
# examples: "&e{player} said: &f{message}", "{player}: {message}", "&l{message}"
bubbleFormat: "{message}"

# row format. Applied for each row.
rowFormat: "&e&l{message}"
